name: Update Major Version Tag After Release

on:
  workflow_dispatch:
    inputs:
      target:
        description: The tag or reference to use
        required: false
        default: "default-tag"
      major_version:
        type: choice
        description: The major version to update
        options:
          - v5
          - v4
          - v3
          - v2
          - v1
  release:
    types:
      - published

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.TAGS_TOKEN }}
    - name: Set Dynamic Environment Variables
      run: |
        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          # Use inputs from workflow_dispatch if provided
          TARGET="${{ github.event.inputs.target }}"
          MAJOR_VERSION="${{ github.event.inputs.major_version }}"
        elif [ "${{ github.event_name }}" == "release" ]; then
          # Use release tag for target, and extract major version
          TARGET="${{ github.event.release.tag_name }}"
          MAJOR_VERSION="$(echo $TARGET | cut -d '.' -f1)"
        fi
        echo "Target tag: $TARGET, Major Version Tag: $MAJOR_VERSION"
        echo "TARGET=$TARGET" >> $GITHUB_ENV
        echo "MAJOR_VERSION=$MAJOR_VERSION" >> $GITHUB_ENV

    - name: Validate tag
      run: |
        # Function to validate a semantic versioning tag
        validate_tag() {
          local tag="${{ env.TARGET }}"

          # Regular expression for validating semantic versioning tag
          local semver_regex="^([0-9]+)\.([0-9]+)\.([0-9]+)(-[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?(\+[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$"

          if [[ $tag =~ $semver_regex ]]; then
            echo "Tag '$tag' is valid according to Semantic Versioning."
            return 0
          else
            echo "Tag '$tag' is NOT valid according to Semantic Versioning."
            return 1
          fi
        }

        tag="$1"
        validate_tag "$tag"

    - name: Git config
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
    - name: Tag new target
      run: git tag -f ${{ env.MAJOR_VERSION }} ${{ env.TARGET }}
    - name: Push new tag
      run: git push origin ${{ env.MAJOR_VERSION }} --force